version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: tureader/Dockerfile
    command: sh -c "cd tureader && gunicorn tureader.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
      - static_volume:/code/tureader/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/tureader/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
