# Generated by Django 2.2.2 on 2019-09-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(default='-', max_length=100)),
                ('phd', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('edu', models.TextField()),
                ('spc', models.TextField()),
                ('contact', models.TextField()),
                ('uni', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=100)),
                ('tel', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=100)),
                ('spc_field', models.TextField()),
                ('source', models.CharField(max_length=100)),
            ],
        ),
    ]
