# Generated by Django 2.2.5 on 2020-01-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='contact',
            field=models.TextField(verbose_name='สถานที่ติดต่อ'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='edu',
            field=models.TextField(verbose_name='คุณวุฒิ'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='อีเมล'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='field',
            field=models.CharField(max_length=100, verbose_name='สาขาวิชา'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='ชื่อ'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='สกุล'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='phd',
            field=models.CharField(max_length=100, verbose_name='ตำแหน่ง ป.เอก'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='rank',
            field=models.CharField(default='-', max_length=100, verbose_name='ตำแหน่งทางวิชาการ'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='source',
            field=models.CharField(max_length=100, verbose_name='แหล่งที่มา'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='spc',
            field=models.TextField(verbose_name='ความเชี่ยวชาญ'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='spc_field',
            field=models.TextField(verbose_name='สาขาวิชาตาม ก.พ.อ.'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='status',
            field=models.CharField(max_length=100, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='tel',
            field=models.TextField(verbose_name='โทร.'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='uni',
            field=models.CharField(max_length=200, verbose_name='มหาวิทยาลัย'),
        ),
    ]
